# Username (twitter handle of the person who hosts this bot)
username: username

# Sleep time (in minutes)
sleep_time: 15

# Image directory
image_directory: IMAGE_DIRECTORY

# Twitter configuration
twitter:
  consumer_key: YOUR_KEYS_HERE
  consumer_secret: YOUR_KEYS_HERE
  access_token: YOUR_KEYS_HERE
  access_token_secret: YOUR_KEYS_HERE
